name: CI
on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install testing tools
        run: pip install -r test/requirements.txt
      - name: Build and test service
        run: make all
