name: Build and test of systemd-rest project
on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install testing tools
        run: |
          cd test
          pip install -r requirements.txt
      - name: Build and test service
        run: make all
